name: solarease
description: SolarEase app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.0
  google_maps_flutter: ^2.2.5 
  geolocator: ^9.0.2
  geocoding: ^3.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  provider: ^6.0.0
  intl: ^0.19.0
  http: ^1.1.0
  dio: ^5.3.0
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true